Get one document
wooly905/pulsarkeywordsearch pull request #16
Opened 2023-05-30 07:59 UTC by jennyesoo

104250 - Write code : update one document function

2023-05-31 02:18 UTC, wooly905 requested changes
Please update the code and then sent a new PR.

2023-05-31 02:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataReader/ChangeRequestReader.cs
> +        IEnumerable<CommonDataModel> changeRequest = await GetChangeRequestAsync(changeRequestId);
There is a bug here.
The collection may contain no element when change request id doesn't exist in database.
When the collection is empty, you should not continue to process the collection and then you should return null. 
Also, you need to make sure that callers can handle null object well.

2023-05-31 02:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataReader/ComponentRootReader.cs
> +        IEnumerable<CommonDataModel> componentRoot = await GetComponentRootAsync(componentRootId);
Same problem here.
I don't repeat the same problem again in the following code.
You have to update all of them.

2023-05-31 02:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataReader/ChangeRequestReader.cs
> +    private async Task<IEnumerable<CommonDataModel>> GetChangeRequestAsync(int changeRequestId)
I don't think this is a good function.
When an id was entered, we expected that only one element will be returned. So the return type should not be "collection" type. It should be justCommonDataModel.

Fix the problem for all of the code in other target.

2023-06-02 03:52 UTC, jennyesoo commented
Update:
1. 新增UpdateClient，根據使用者輸入的SearchType去更新Type項目，並呼叫Type的Orchestrator。
2. 每個Orchestrator, Reader, Transformer已多新增給<CommonDataModel>使用的function。
3. 已新增當CommonDataModel為空項目時，就不進行之後動作。

2023-06-02 06:18 UTC, wooly905 approved these changes
Resolve all comments and then merge to dev.
If any, ping me.

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataReader/ProductReader.cs
> +        if (int.TryParse(product.GetValue("ProductId"), out int productId))
same here, code style.

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataTransformation/ChangeRequestDataTransformer.cs
> +    public CommonDataModel Transform(CommonDataModel changeRequest)
Input can be null. You need to handle this case.

All public functions must verify all arguments to make sure that they are valid to be processed in this function.
This is coding 101. You need to keep in mind for always.

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataTransformation/ComponentRootTransformer.cs
> +    public CommonDataModel Transform(CommonDataModel componentRoot)
Same problem here, verify input.

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataTransformation/ComponentVersionDataTransformer.cs
> +    public CommonDataModel Transform(CommonDataModel rootversion)
Same here. verify input.

argument name -> version 
Don't say rootversion, I can't tell it's root or version.

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataTransformation/FeatureDataTransformer.cs
> +    public CommonDataModel Transform(CommonDataModel feature)
Same problem here.

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataTransformation/HpAMOPartNumberDataTransformer.cs
> +    public CommonDataModel Transform(CommonDataModel partNumber)
Same problem here

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataTransformation/ProductDataTransformer.cs
> +    public CommonDataModel Transform(CommonDataModel product)
Same problem here

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/DataTransformation/ProductDropDataTransformer.cs
> +    {
Same problem here.

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/Orchestrator/ChangeRequestOrchestrator.cs
> +    public async Task InitializeAsync(int changeRequestId)
I don't think we need this. Init is to make everything from scratch, which means Meilisearch is empty. Init will read many things from PRS and write the things to Meilisearch.
We don't init one single thing. It's not called init. It's "update".
We will implement UpdateClient later. So remove the function now.

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/Orchestrator/ComponentRootOrchestrator.cs
> +    public async Task InitializeAsync(int rootId)
Same too

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/Orchestrator/ComponentVersionOrchestrator.cs
> +    public async Task InitializeAsync(int componentVersionId)
Same too

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/Orchestrator/FeatureOrchestrator.cs
> +    public async Task InitializeAsync(int featureId)
Same too

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/Orchestrator/HpAMOPartNumberOrchestrator.cs
> +    public async Task InitializeAsync(int hpAMOPartNumberId)
Same too

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/Orchestrator/IInitializationOrchestrator.cs
> +    public Task InitializeAsync(int id);
Remove

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/Orchestrator/ProductDropOrchestrator.cs
> +    public async Task InitializeAsync(int productDropId)
Remove

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/Orchestrator/ProductOrchestrator.cs
> +    public async Task InitializeAsync(int productId)
Remove

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/SearchEngine/MeiliSearchClient.cs
> +    public async Task SendElementsUpdateAsync(CommonDataModel element)
Method name -> SendElementUpdationAsync

2023-06-02 06:18 UTC, wooly905 commented on HP.Pulsar.Search.Keyword/UpdateEngine/UpdateClient.cs
> +    {
Remove this file. We are not here yet.

2023-06-02 06:18 UTC, wooly905 commented on KeywordSearchInitializationConsole/Program.cs
> +        UpdateClient updateClient = new UpdateClient(info);
Keep them commented. We don't implement it now.

2023-06-02 06:18 UTC, wooly905 commented on KeywordSearchInitializationConsole/Program.cs
> +using HP.Pulsar.Search.Keyword.UpdateEngine;
Remove

2023-06-02 06:19 UTC, wooly905 approved these changes
Resolve all comments and then merge to dev.
If any, ping me.

2023-06-05 03:18 UTC, wooly905 commented
@jennyesoo 
Can you please resolve the conflict and merge again?

2023-06-05 03:22 UTC, jennyesoo commented
> @jennyesoo Can you please resolve the conflict and merge again?

Sure, I am currently working on it.

2023-06-05 04:34 UTC, merged